name: wakatime

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:

jobs:
  update-readme:
    env:
      PR_BRANCH: wakatime-${{ github.sha }}
    name: wakatime
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Create Branch
        id: branch
        run: |
          git checkout -b ${{ env.PR_BRANCH }}
          git push origin ${{ env.PR_BRANCH }}
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_TOKEN }} # required
          TIME_RANGE: all_time # optional
          LANG_COUNT: 10 # optional
          TARGET_BRANCH: ${{ env.PR_BRANCH }}
          COMMIT_MESSAGE: "chore: update wakatime stats"
      - name: Create PR
        run: |
          gh pr create --base main --head ${{ env.PR_BRANCH }} --title 'chore: update wakatime stats [skip-ci]' --body "" >/dev/null 2>&1
          gh pr view ${{ env.PR_BRANCH }} >/dev/null 2>&1 && gh pr merge --squash --admin ${{ env.PR_BRANCH }} || echo "PR does not exist."
          git push -d origin ${{ env.PR_BRANCH }} >/dev/null 2>&1
        env:
          GH_TOKEN: ${{ secrets.GH_OWNER_TOKEN }}
