name: wakatime

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main]

jobs:
  update-readme:
    env:
      PR_BRANCH: wakatime-${{ github.sha }}
    name: wakatime
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      
      - name: Create Branch
        id: branch
        run: |
          git checkout -b ${{ env.PR_BRANCH }}
          git push origin ${{ env.PR_BRANCH }}

      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_TOKEN }}
          API_BASE_URL: https://hackatime.hackclub.com/api
          TIME_RANGE: all_time
          LANG_COUNT: 10
          TARGET_BRANCH: ${{ env.PR_BRANCH }}
          COMMIT_MESSAGE: "chore: update wakatime stats"

      - name: Check for New Commits on PR Branch
        id: check-new-commits
        run: |
          # Fetch the latest commit SHA for the PR branch and compare it with the main branch
          LATEST_MAIN_SHA=$(git rev-parse origin/main)
          LATEST_PR_SHA=$(git rev-parse HEAD)

          # Check if there’s a difference
          if [ "$LATEST_MAIN_SHA" != "$LATEST_PR_SHA" ]; then
            echo "has_changes=true" >> $GITHUB_ENV
          else
            echo "has_changes=false" >> $GITHUB_ENV
          fi

      - name: Create PR
        if: env.has_changes == 'true'
        run: |
          gh pr create --base main --head ${{ env.PR_BRANCH }} --title 'chore: update wakatime stats [skip-ci]' --body ""
        env:
          GH_TOKEN: ${{ secrets.GH_BOT_TOKEN }}

      - name: Merge PR
        if: env.has_changes == 'true'
        run: |
          gh pr view ${{ env.PR_BRANCH }}
          gh pr merge --squash --admin ${{ env.PR_BRANCH }}
        env:
          GH_TOKEN: ${{ secrets.GH_OWNER_TOKEN }}

      - name: Delete Branch
        run: |
          git push -d origin ${{ env.PR_BRANCH }}
