name: wakatime

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:

jobs:
  update-readme:
    env:
      PR_BRANCH: wakatime-${{ github.sha }}
    name: wakatime
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Create Branch
        id: branch
        run: |
          git checkout -b ${{ env.PR_BRANCH }}
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_TOKEN }} # required
          TIME_RANGE: all_time # optional
          LANG_COUNT: 10 # optional
          TARGET_BRANCH: ${{ env.PR_BRANCH }}
          COMMIT_MESSAGE: "chore: update wakatime stats"
      - name: Check if there are changes
        id: changes
        uses: UnicornGlobal/has-changes-action@ea00e6f831a9e785271645729fa251907b314707 # v1.0.12
      - name: Create PR
        if: steps.changes.outputs.changed == 1
        run: |
          git push origin ${{ env.PR_BRANCH }}
          gh pr create --base main --head ${{ env.PR_BRANCH }} --title 'chore: update wakatime stats [skip-ci]' --body ""
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Merge PR
        if: steps.changes.outputs.changed == 1
        run: |
          gh pr merge --squash --admin --delete-branch ${{ env.PR_BRANCH }}
        env:
          GH_TOKEN: ${{ secrets.GH_OWNER_TOKEN }}
